name: Verify and Extract Performance

on:
  push:
    paths:
      - 'Algos/**/*.gz'

jobs:
  verify:
    runs-on: ubuntu-latest
    steps: 
    
    - name: Checkout repository
      uses: actions/checkout@v3

      # checkout is used here as its more clean and it guarrantees that we get the version we want and that all context is maintained.
    - name: Checkout Verifier Repository
      uses: actions/checkout@v4
      with:
        repository: GraphVertexColoring/coloring-verifier
        path: coloring-verifier  # Clone this into a subdirectory
    
    - name: Checkout gvc-instances
      uses: actions/checkout@v4
      with:
        repository: GraphVertexColoring/gvc-instances
        path: gvc-instances
    
    - name: Set up Make and GCC
      run: sudo apt-get install build-essential # this ensures make and gcc are installed
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with: 
        python-version: '3.10'

    - name: Build Verifier and Make Executable
      run: |
        cd coloring-verifier/src
        make CC=gcc
        chmod +x coloring-verifier

    - name: Verify solutions
      run: | # script here that runs per algo in the Algos directory
        # figure out a valid "old" reference for diff
        if git rev-parse --verify HEAD~1 >/dev/null 2>&1; then
          base=HEAD~1
        else
          # empty tree hash: treat this as the very first diff
          base=$(git hash-object -t tree /dev/null)
        fi

        # find new or modified Algos
        changed_dirs=$(git diff --name-only --diff-filter=AM "$base" HEAD \
                      | grep '^Algos/' \
                      | awk -F/ '{print $2"/"$3}' \
                      | sort -u)

        echo "Running verification on updated solutions..."

        for dir in $changed_dirs; do
          echo "Verifying solutions in Algos/$dir..."
          python .github/scripts/verify.py "Algos/$dir" 
        done

  extract_performance:
    runs-on: ubuntu-latest
    needs: verify
    
    steps: 
    - name: Checkout data-archive
      uses: actions/checkout@v4

    - name: Checkout Performance Extractor Repository
      uses: actions/checkout@v4
      with:
        repository: GraphVertexColoring/gvc-perf
        path: gvc-perf
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with: 
        python-version: '3.10'

    - name: Clone coloring Repository
      run: |
        git clone https://x-access-token:${{ secrets.ORG_PAT }}@github.com/GraphVertexColoring/coloring.git
    
    # Noticed a problem here where if you rerun it even with a non allowed instance it will still work since this doesnt only run on the new algorithms.
    - name: Extract Performance
      working-directory: gvc-perf
      run: |
        python performance_extractor.py 

    - name: Update Best
      run: |
        python update_best.py
      working-directory: .github/scripts

    - name: Push Results to coloring Repo
      run: |
        cd coloring
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        git add Resources
        git commit -m "Automated Performance Extraction Results" || echo "No changes to commit" 
        git push origin master